export const SEO_CONFIG = {
    title: 'Hellofixo - Fast, Private, Offline PDF & Image Tools',
    description: '100% client-side PDF and Image tools by Hellofixo. Merge, split, compress, resize, and convert files without uploading them to any server.',
    url: 'https://toolkit.example.com',
    keywords: [
        'merge pdf free',
        'compress pdf online',
        'compress image offline',
        'resize image browser',
        'remove background ai free',
        'jpg to png converter',
        'pdf tools without upload',
    ],
    categories: [
        { id: 'pdf', name: 'PDF Tools' },
        { id: 'image', name: 'Image Tools' },
        { id: 'advanced', name: 'Advanced AI Tools' },
        { id: 'security', name: 'Security & Privacy' },
        { id: 'utility', name: 'Utility Tools' },
    ],
    tools: [
        // PDF Tools
        {
            id: 'merge',
            name: 'Merge PDF',
            path: '/merge-pdf',
            description: 'Combine multiple PDF files into one easily.',
            icon: 'Merge',
            category: 'pdf',
        },
        {
            id: 'split',
            name: 'Split PDF',
            path: '/split-pdf',
            description: 'Extract pages from a PDF or save each page as a separate PDF.',
            icon: 'Scissors',
            category: 'pdf',
        },
        {
            id: 'compress-pdf',
            name: 'Compress PDF',
            path: '/compress-pdf',
            description: 'Reduce the file size of your PDF while maintaining quality.',
            icon: 'Minimize2',
            category: 'pdf',
        },
        {
            id: 'pdf-to-jpg',
            name: 'PDF to JPG',
            path: '/pdf-to-jpg',
            description: 'Convert each PDF page into a high-quality JPG image.',
            icon: 'FileImage',
            category: 'pdf',
        },
        {
            id: 'jpg-to-pdf',
            name: 'Image to PDF',
            path: '/jpg-to-pdf',
            description: 'Convert images into a single professional PDF file.',
            icon: 'ImagePlus',
            category: 'pdf',
        },
        {
            id: 'sign-pdf',
            name: 'Sign PDF',
            path: '/sign-pdf',
            description: 'Draw or upload your signature and add it to PDF pages.',
            icon: 'PenTool',
            category: 'pdf',
        },
        {
            id: 'lock-pdf',
            name: 'Lock PDF',
            path: '/lock-pdf',
            description: 'Password protect your sensitive PDF documents.',
            icon: 'Lock',
            category: 'security',
        },
        {
            id: 'unlock-pdf',
            name: 'Unlock PDF',
            path: '/unlock-pdf',
            description: 'Remove password protection from encrypted PDFs.',
            icon: 'Unlock',
            category: 'security',
        },
        // Image Tools
        {
            id: 'compress-image',
            name: 'Compress Image',
            path: '/compress-image',
            description: 'Reduce image size (JPG, PNG, WebP) without losing quality.',
            icon: 'FileArchive',
            category: 'image',
        },
        {
            id: 'resize-image',
            name: 'Resize Image',
            path: '/resize-image',
            description: 'Change image dimensions with perfect aspect ratio.',
            icon: 'Maximize',
            category: 'image',
        },
        {
            id: 'crop-image',
            name: 'Crop Image',
            path: '/crop-image',
            description: 'Crop images to specific ratios or custom areas.',
            icon: 'Crop',
            category: 'image',
        },
        {
            id: 'convert-image',
            name: 'Convert Format',
            path: '/convert-image',
            description: 'Convert between JPG, PNG, and WebP instantly.',
            icon: 'ArrowLeftRight',
            category: 'image',
        },
        {
            id: 'rotate-image',
            name: 'Rotate / Flip',
            path: '/rotate-image',
            description: 'Rotate images or flip them horizontally/vertically.',
            icon: 'RotateCw',
            category: 'image',
        },
        {
            id: 'watermark-image',
            name: 'Add Watermark',
            path: '/watermark-image',
            description: 'Overlay text or images as watermarks on your photos.',
            icon: 'Stamp',
            category: 'image',
        },
        {
            id: 'passport-photo',
            name: 'Passport Photo Maker',
            path: '/passport-photo',
            description: 'Create perfect passport size photos for India, USA, and more.',
            icon: 'UserSquare',
            category: 'image',
        },
        {
            id: 'resize-kb',
            name: 'Resize to KB',
            path: '/resize-kb',
            description: 'Reduce image size to exact KB targets (20KB, 50KB) for gov forms.',
            icon: 'Database',
            category: 'image',
        },
        {
            id: 'convert-ico',
            name: 'ICO Converter',
            path: '/convert-ico',
            description: 'Convert any image to ICO format for website favicons.',
            icon: 'ExternalLink',
            category: 'utility',
        },
        {
            id: 'qr-generator',
            name: 'QR Code Generator',
            path: '/qr-generator',
            description: 'Generate high-quality QR codes for URLs, text, or Wi-Fi.',
            icon: 'QrCode',
            category: 'utility',
        },
        {
            id: 'image-to-base64',
            name: 'Image to Base64',
            path: '/image-to-base64',
            description: 'Convert images to Base64 strings for code embedding.',
            icon: 'Code',
            category: 'utility',
        },
        // Advanced Tools
        {
            id: 'remove-bg',
            name: 'Remove Background',
            path: '/remove-bg',
            description: 'AI-powered background removal running entirely in your browser.',
            icon: 'Eraser',
            category: 'advanced',
        },
        {
            id: 'image-filters',
            name: 'Filters & Adjust',
            path: '/image-filters',
            description: 'Adjust brightness, contrast, blur, and apply filters.',
            icon: 'Sliders',
            category: 'advanced',
        },
        {
            id: 'remove-exif',
            name: 'Remove Metadata',
            path: '/remove-exif',
            description: 'Privacy tool to strip EXIF data and metadata from images.',
            icon: 'ShieldOff',
            category: 'advanced',
        },
        {
            id: 'internet-speed-test',
            name: 'Internet Speed Test',
            path: '/internet-speed-test',
            description: 'Check your download, upload speed and latency instantly.',
            icon: 'Wifi',
            category: 'utility',
        },
    ],
};
